# Generated by Django 6.0.7 on 2026-07-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
