# Generated by Django 6.0.7 on 2026-07-23 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournament_players_alter_tournament_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_correct_goals_per_team', models.IntegerField(default=2, verbose_name='Match: Correct goals per team')),
                ('match_correct_total_goals', models.IntegerField(default=3, verbose_name='Match: Correct total goals')),
                ('match_correct_1x2', models.IntegerField(default=3, verbose_name='Match: Correct outcome (1X2)')),
                ('group_correct_placement', models.IntegerField(default=3, verbose_name='Group Stage: Correct placement')),
                ('group_correct_points', models.IntegerField(default=2, verbose_name='Group Stage: Correct points')),
                ('group_correct_goals_scored', models.IntegerField(default=1, verbose_name='Group Stage: Correct goals scored')),
                ('group_correct_goals_conceded', models.IntegerField(default=1, verbose_name='Group Stage: Correct goals conceded')),
                ('group_correct_goal_diff', models.IntegerField(default=1, verbose_name='Group Stage: Correct goal difference (+/-)')),
                ('knockout_qualified_third', models.IntegerField(default=2, verbose_name='Knockout: Correct team qualified as third')),
                ('knockout_round_of_16', models.IntegerField(default=2, verbose_name='Knockout: Correct team in Round of 16')),
                ('knockout_quarterfinal', models.IntegerField(default=4, verbose_name='Knockout: Correct team in Quarterfinal')),
                ('knockout_semifinal', models.IntegerField(default=6, verbose_name='Knockout: Correct team in Semifinal')),
                ('knockout_bronze_match', models.IntegerField(default=8, verbose_name='Knockout: Correct team in Bronze Match')),
                ('knockout_final', models.IntegerField(default=8, verbose_name='Knockout: Correct team in Final')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point_system', to='tournament.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Sidebet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Sidebet Question')),
                ('points', models.IntegerField(default=30, verbose_name='Points')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sidebets', to='tournament.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='SidebetAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_answer', models.CharField(max_length=150)),
                ('is_correct', models.BooleanField(default=False)),
                ('sidebet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tournament.sidebet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
