# Generated by Django 6.0.7 on 2026-07-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_matchprediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsystem',
            name='knockout_qualified_third',
            field=models.IntegerField(default=2, verbose_name='Knockout: Correct team qualified to '),
        ),
    ]
