# Generated by Django 6.0.7 on 2026-07-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_alter_pointsystem_knockout_qualified_third'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsystem',
            name='group_correct_goal_diff',
            field=models.IntegerField(default=1, verbose_name='Correct goal difference (+/-)'),
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='group_correct_goals_conceded',
            field=models.IntegerField(default=1, verbose_name='Correct goals conceded'),
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='group_correct_goals_scored',
            field=models.IntegerField(default=1, verbose_name='Correct goals scored'),
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='group_correct_placement',
            field=models.IntegerField(default=3, verbose_name='Correct placement'),
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='group_correct_points',
            field=models.IntegerField(default=2, verbose_name='Correct points'),
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='knockout_bronze_match',
            field=models.IntegerField(default=8, verbose_name='Correct team in Bronze Match'),
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='knockout_final',
            field=models.IntegerField(default=8, verbose_name='Correct team in Final'),
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='knockout_qualified_third',
            field=models.IntegerField(default=2, verbose_name='Correct team qualified to '),
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='knockout_quarterfinal',
            field=models.IntegerField(default=4, verbose_name='Correct team in Quarterfinal'),
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='knockout_round_of_16',
            field=models.IntegerField(default=2, verbose_name='Correct team in Round of 16'),
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='knockout_semifinal',
            field=models.IntegerField(default=6, verbose_name='Correct team in Semifinal'),
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='match_correct_1x2',
            field=models.IntegerField(default=3, verbose_name='Correct outcome (1X2)'),
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='match_correct_goals_per_team',
            field=models.IntegerField(default=2, verbose_name='Correct goals per team'),
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='match_correct_total_goals',
            field=models.IntegerField(default=3, verbose_name='Correct total goals'),
        ),
    ]
