# Generated by Django 6.0.7 on 2026-07-23 22:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_alter_pointsystem_group_correct_goal_diff_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['match_number']},
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='match_date',
        ),
        migrations.RemoveField(
            model_name='matchprediction',
            name='points_awarded',
        ),
        migrations.RemoveField(
            model_name='matchprediction',
            name='predicted_away_score',
        ),
        migrations.RemoveField(
            model_name='matchprediction',
            name='predicted_home_score',
        ),
        migrations.RemoveField(
            model_name='matchprediction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sidebet',
            name='points',
        ),
        migrations.RemoveField(
            model_name='sidebetanswer',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='sidebetanswer',
            name='player_answer',
        ),
        migrations.RemoveField(
            model_name='sidebetanswer',
            name='user',
        ),
        migrations.AddField(
            model_name='match',
            name='away_goals',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='match',
            name='home_goals',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='match_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.CharField(default='TBD', max_length=200),
        ),
        migrations.AddField(
            model_name='matchprediction',
            name='away_goals',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchprediction',
            name='home_goals',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchprediction',
            name='player',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='match_predictions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sidebetanswer',
            name='answer',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sidebetanswer',
            name='player',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sidebet_answers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.CharField(default='TBD', max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.CharField(default='TBD', max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament.tournament'),
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='group_correct_goal_diff',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='group_correct_goals_conceded',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='group_correct_goals_scored',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='group_correct_placement',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='group_correct_points',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='knockout_bronze_match',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='knockout_final',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='knockout_qualified_third',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='knockout_quarterfinal',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='knockout_round_of_16',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='knockout_semifinal',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='match_correct_1x2',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='match_correct_goals_per_team',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='match_correct_total_goals',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sidebet',
            name='question',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='participating_tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_groups', to='tournament.tournament')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament.group'),
        ),
        migrations.CreateModel(
            name='KnockoutStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knockout_stages', to='tournament.tournament')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament.knockoutstage'),
        ),
    ]
