# Generated by Django 6.0.7 on 2026-07-23 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_alter_match_options_remove_match_away_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchprediction',
            name='away_goals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchprediction',
            name='home_goals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournament.group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
