# Generated by Django 6.0.7 on 2026-07-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_alter_matchprediction_away_goals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(blank=True, help_text="Ex: 'se' för Sverige, 'gb-eng' för England", max_length=10, null=True),
        ),
    ]
