# Generated by Django 6.0.7 on 2026-07-23 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_group_team1_code_group_team1_name_group_team2_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='team1_code',
        ),
        migrations.RemoveField(
            model_name='group',
            name='team1_name',
        ),
        migrations.RemoveField(
            model_name='group',
            name='team2_code',
        ),
        migrations.RemoveField(
            model_name='group',
            name='team2_name',
        ),
        migrations.RemoveField(
            model_name='group',
            name='team3_code',
        ),
        migrations.RemoveField(
            model_name='group',
            name='team3_name',
        ),
        migrations.RemoveField(
            model_name='group',
            name='team4_code',
        ),
        migrations.RemoveField(
            model_name='group',
            name='team4_name',
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, help_text='Auto-detected from name if left blank', max_length=10, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournament.group')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournament.tournament')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
