# Generated by Django 6.0.7 on 2026-07-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_remove_group_team1_code_remove_group_team1_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='backdrop',
            field=models.ImageField(blank=True, help_text='Header backdrop background', null=True, upload_to='tournament/backdrops/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='icon',
            field=models.ImageField(blank=True, help_text='Tournament emblem/favicon', null=True, upload_to='tournament/icons/'),
        ),
    ]
