# Generated by Django 6.0.7 on 2026-07-27 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0016_remove_match_venue_match_is_finished_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tournamentsubmission',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournamentsubmission',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tournament.tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentsubmission',
            unique_together={('tournament', 'player')},
        ),
    ]
