# Generated by Django 6.0.7 on 2026-07-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0017_tournamentsubmission_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchprediction',
            name='penalty_winner',
            field=models.CharField(blank=True, help_text='Tiebreaker winner team name', max_length=100, null=True),
        ),
    ]
