# Generated by Django 6.0.7 on 2026-07-27 19:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0018_matchprediction_penalty_winner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebet',
            name='correct_answers',
            field=models.TextField(blank=True, help_text='Anges av admin. Separera flera giltiga/oavgjorda svar med kommatecken (t.ex. Mbappé, Isak, Haaland)', null=True, verbose_name='Rätt svar'),
        ),
        migrations.AddField(
            model_name='sidebet',
            name='points',
            field=models.PositiveIntegerField(default=5, verbose_name='Poäng för rätt svar'),
        ),
        migrations.AddField(
            model_name='sidebet',
            name='question_type',
            field=models.CharField(choices=[('TEAM', 'Välj lag (dropdown)'), ('TEXT', 'Fritext (t.ex. spelarnamn)')], default='TEXT', max_length=10, verbose_name='Frågetyp'),
        ),
        migrations.AlterField(
            model_name='sidebet',
            name='question',
            field=models.CharField(max_length=255, verbose_name='Fråga'),
        ),
        migrations.AlterField(
            model_name='sidebetanswer',
            name='answer',
            field=models.CharField(max_length=255, verbose_name='Svar'),
        ),
        migrations.AlterUniqueTogether(
            name='sidebetanswer',
            unique_together={('sidebet', 'player')},
        ),
    ]
