# Generated by Django 6.0.7 on 2026-07-28 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0019_sidebet_correct_answers_sidebet_points_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sidebet',
            options={'verbose_name': 'Bonusfråga', 'verbose_name_plural': 'Bonusfrågor'},
        ),
        migrations.AlterModelOptions(
            name='sidebetanswer',
            options={'verbose_name': 'Spelarens bonussvar', 'verbose_name_plural': 'Spelarnas bonussvar'},
        ),
    ]
