# Generated by Django 6.0.7 on 2026-07-29 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0020_alter_sidebet_options_alter_sidebetanswer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banned_phrases', models.JSONField(default=list, help_text='List of overused phrases forbidden in LLM prompts')),
            ],
            options={
                'verbose_name': 'Editorial Settings',
                'verbose_name_plural': 'Editorial Settings',
            },
        ),
        migrations.CreateModel(
            name='StyleExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(help_text='Hand-written Swedish roast example for LLM tone calibration')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Style Example (Tone Calibration)',
                'verbose_name_plural': 'Style Examples (Tone Calibration)',
            },
        ),
        migrations.CreateModel(
            name='InsightEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ELIMINATION', 'Elimination'), ('BIG_MOVER', 'Big Mover / Rank Swing'), ('PREDICTION_AGED_POORLY', 'Prediction Aged Poorly'), ('FAILED_BANKER', 'Failed Banker'), ('OUTLIER_VICTORY', 'Outlier Victory'), ('GENERAL_DRAMA', 'General Drama')], default='GENERAL_DRAMA', max_length=50)),
                ('player_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(help_text="Event details, e.g., 'Lucas dropped from 1st to 5th place.'")),
                ('importance_score', models.IntegerField(default=50, help_text='Score from 0-100 indicating narrative importance')),
                ('matchday_reference', models.IntegerField(blank=True, help_text='Matchday number or reference', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insight_events', to='tournament.tournament')),
            ],
            options={
                'verbose_name': 'Insight Event',
                'verbose_name_plural': 'Insight Events',
                'ordering': ['-importance_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaticInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CONSENSUS_ALERT', 'Consensus Alert'), ('CERTIFIED_MADNESS', 'Certified Madness'), ('LONE_WOLF', 'Lone Wolf'), ('DELUSION_INDEX', 'Delusion Index'), ('GENERAL', 'General Insight')], default='GENERAL', max_length=50)),
                ('player_name', models.CharField(blank=True, max_length=100, null=True)),
                ('data_point', models.TextField(help_text="Factual summary, e.g., '12 of 13 players have Spain winning Group C.'")),
                ('llm_roast', models.TextField(help_text='LLM-generated Swedish joke/commentary')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='static_insights', to='tournament.tournament')),
            ],
            options={
                'verbose_name': 'Static Insight (Almanac)',
                'verbose_name_plural': 'Static Insights (Almanac)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorylineMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('narrative', models.TextField(help_text="Ongoing story arc, e.g., 'Lucas heavily backed Belgium, but they failed.'")),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storyline_memories', to='tournament.tournament')),
            ],
            options={
                'verbose_name': 'Storyline Memory',
                'verbose_name_plural': 'Storyline Memories',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='DailyGazette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateField(db_index=True)),
                ('headline', models.CharField(help_text='Bold headline in Swedish', max_length=255)),
                ('tagline', models.CharField(help_text='Sub-headline / hook in Swedish', max_length=255)),
                ('image_url', models.CharField(blank=True, help_text='Path or URL to generated visual asset', max_length=500, null=True)),
                ('image_prompt', models.TextField(blank=True, help_text='Audit log of image prompt used', null=True)),
                ('content_format', models.CharField(choices=[('STANDARD_COLUMN', 'Standard Column (2 short narrative paragraphs)'), ('WINNERS_LOSERS', 'Winners & Losers (Bulleted list of 1-sentence roasts)'), ('INTERVIEW', 'Interview (Fake Q&A transcript)'), ('PUB_QUOTES', 'Pub Quotes (Overheard Swedish pub commentary)')], default='STANDARD_COLUMN', max_length=50)),
                ('content', models.TextField(help_text='Full daily article in Swedish')),
                ('tone_used', models.CharField(blank=True, help_text='e.g. Dry Scandinavian, Tabloid, Pub Quotes', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_gazettes', to='tournament.tournament')),
            ],
            options={
                'verbose_name': 'Daily Gazette Edition',
                'verbose_name_plural': 'Daily Gazette Editions',
                'ordering': ['-publish_date'],
                'unique_together': {('tournament', 'publish_date')},
            },
        ),
    ]
