# Generated by Django 6.0.7 on 2026-07-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0021_editorialsettings_styleexample_insightevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailygazette',
            name='content_format',
            field=models.CharField(choices=[('STANDARD_COLUMN', 'Standardkrönika'), ('WINNERS_LOSERS', 'Vinnare & Förlorare'), ('INTERVIEW', 'Exklusiv Intervju'), ('PUB_QUOTES', 'Citat från Puben')], default='STANDARD_COLUMN', max_length=50),
        ),
        migrations.AlterField(
            model_name='insightevent',
            name='type',
            field=models.CharField(choices=[('ELIMINATION', 'Utslagning'), ('BIG_MOVER', 'Klassklättrare / Raskt Fall'), ('PREDICTION_AGED_POORLY', 'Tips Som Åldrades Dåligt'), ('FAILED_BANKER', 'Spikkrasch'), ('OUTLIER_VICTORY', 'Soloseger'), ('GENERAL_DRAMA', 'Omgångsdrama')], default='GENERAL_DRAMA', max_length=50),
        ),
        migrations.AlterField(
            model_name='staticinsight',
            name='category',
            field=models.CharField(choices=[('CONSENSUS_ALERT', 'Konsensusvarning'), ('CERTIFIED_MADNESS', 'Verifierad Galenskap'), ('LONE_WOLF', 'Ensam Varg'), ('DELUSION_INDEX', 'Övermodsindex'), ('GENERAL', 'Allmän Insikt')], default='GENERAL', max_length=50),
        ),
    ]
