# Generated by Django 6.0.7 on 2026-07-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0023_alter_pointsystem_match_correct_goals_per_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailygazette',
            name='structured_data',
            field=models.JSONField(blank=True, default=dict, help_text='Structured layout payload: top_story, events_grid, day_summary'),
        ),
    ]
