# Generated by Django 6.0.7 on 2026-07-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0024_dailygazette_structured_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailygazette',
            name='primary_posture',
            field=models.CharField(blank=True, help_text="Posture key for primary avatar, e.g. 'Knee'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dailygazette',
            name='rival_posture',
            field=models.CharField(blank=True, help_text="Posture key for rival avatar, always 'Rival-left'", max_length=50, null=True),
        ),
    ]
