# Generated by Django 6.0.7 on 2026-08-03 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0025_dailygazette_primary_posture_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailygazette',
            name='analysis_outlook',
            field=models.TextField(blank=True, help_text='ANALYSIS: AI predictions of opportunities & threats', null=True),
        ),
        migrations.AddField(
            model_name='dailygazette',
            name='featured_players_json',
            field=models.JSONField(blank=True, default=list, help_text='List of 3 featured player names & postures'),
        ),
        migrations.AddField(
            model_name='dailygazette',
            name='headline_standout_results',
            field=models.TextField(blank=True, help_text='HEADLINE 2: Impactful match results & full scores', null=True),
        ),
        migrations.AddField(
            model_name='dailygazette',
            name='headline_top_contenders',
            field=models.TextField(blank=True, help_text='HEADLINE 1: Top contenders, rivalry & banter', null=True),
        ),
        migrations.AddField(
            model_name='dailygazette',
            name='headline_worst_performers',
            field=models.TextField(blank=True, help_text='HEADLINE 3: Fallers & worst performers in period', null=True),
        ),
        migrations.AddField(
            model_name='dailygazette',
            name='is_special_edition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailygazette',
            name='round_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailygazette',
            name='round_number',
            field=models.IntegerField(blank=True, help_text='Round milestone 1 to 9', null=True),
        ),
        migrations.AlterField(
            model_name='dailygazette',
            name='content_format',
            field=models.CharField(choices=[('STANDARD_COLUMN', 'Standardkrönika'), ('WINNERS_LOSERS', 'Vinnare & Förlorare'), ('INTERVIEW', 'Exklusiv Intervju'), ('PUB_QUOTES', 'Citat från Puben'), ('SPECIAL_EDITION', 'Specialutgåva Omgång')], default='STANDARD_COLUMN', max_length=50),
        ),
        migrations.CreateModel(
            name='RoundLeaderboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(help_text='Round milestone 1-9')),
                ('round_name', models.CharField(max_length=100)),
                ('rank', models.IntegerField()),
                ('points', models.IntegerField()),
                ('exact_scores_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_snapshots', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_snapshots', to='tournament.tournament')),
            ],
            options={
                'ordering': ['round_number', 'rank'],
                'unique_together': {('tournament', 'round_number', 'player')},
            },
        ),
    ]
