# Generated by Django 6.0.7 on 2026-08-04 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0026_dailygazette_analysis_outlook_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailygazette',
            options={'ordering': ['-publish_date', '-created_at'], 'verbose_name': 'Daily Gazette Edition', 'verbose_name_plural': 'Daily Gazette Editions'},
        ),
        migrations.AlterUniqueTogether(
            name='dailygazette',
            unique_together=set(),
        ),
    ]
