# Generated by Django 6.0.7 on 2026-08-04 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0027_alter_dailygazette_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_selected_tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by_profiles', to='tournament.tournament'),
        ),
    ]
