# Generated by Django 6.0.7 on 2026-08-05 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0028_userprofile_last_selected_tournament'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='🪣', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Bucket Category',
                'verbose_name_plural': 'Bucket Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_selected_tournament',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_herrklubb_member',
            field=models.BooleanField(default=False, help_text='True if user is one of the 11 original Herrklubben members'),
        ),
        migrations.CreateModel(
            name='BucketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Valfri beskrivning av aktiviteten')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tournament.bucketcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bucket_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BucketDream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_dreams', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dreams', to='tournament.bucketitem')),
            ],
            options={
                'verbose_name': 'Bucket Dream (Högsta Dröm)',
                'verbose_name_plural': 'Bucket Dreams (Högsta Dröm)',
            },
        ),
        migrations.CreateModel(
            name='BucketVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker', models.CharField(choices=[('SVART', 'Svart Marker ($100 / 6p)'), ('GRON', 'Grön Marker ($25 / 3p)'), ('ROD', 'Röd Marker ($5 / 2p)')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='tournament.bucketitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bucket Vote',
                'verbose_name_plural': 'Bucket Votes',
            },
        ),
    ]
