# Generated by Django 6.1 on 2026-08-06 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0030_userprofile_avatar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketvote',
            name='marker',
            field=models.CharField(choices=[('SVART', 'Svart Marker (100)'), ('GRON', 'Grön Marker (50)'), ('ROD', 'Röd Marker (25)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profilbild / Avatar'),
        ),
        migrations.CreateModel(
            name='HerrklubbEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Aktivitetsnamn')),
                ('description', models.TextField(blank=True, verbose_name='Beskrivning')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Datum')),
                ('event_time', models.TimeField(blank=True, null=True, verbose_name='Tid')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Plats')),
                ('is_active', models.BooleanField(default=True, help_text='Visas som Nästa Event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tournament.bucketcategory')),
                ('coordinators', models.ManyToManyField(blank=True, related_name='coordinated_events', to=settings.AUTH_USER_MODEL, verbose_name='Samordnare')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Herrklubb Event',
                'verbose_name_plural': 'Herrklubb Events',
                'ordering': ['event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Startdatum')),
                ('end_date', models.DateField(verbose_name='Slutdatum')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Anledning (Valfritt)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hinder / Frånvaro',
                'verbose_name_plural': 'Hinder / Frånvaro',
                'ordering': ['start_date'],
            },
        ),
    ]
