# Generated by Django 6.1 on 2026-08-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0031_alter_bucketvote_marker_alter_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herrklubbevent',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Slutdatum'),
        ),
        migrations.AlterField(
            model_name='herrklubbevent',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='Startdatum'),
        ),
    ]
