# Generated by Django 6.1 on 2026-08-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0032_herrklubbevent_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='box_score_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON payload containing goals, card events, and period timestamps'),
        ),
    ]
