# Generated by Django 6.1 on 2026-08-14 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='🪣', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Bucket Category',
                'verbose_name_plural': 'Bucket Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BucketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Valfri beskrivning av aktiviteten')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='herrklubb.bucketcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bucket_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BucketDream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_dreams', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dreams', to='herrklubb.bucketitem')),
            ],
            options={
                'verbose_name': 'Bucket Dream (Högsta Dröm)',
                'verbose_name_plural': 'Bucket Dreams (Högsta Dröm)',
            },
        ),
        migrations.CreateModel(
            name='BucketVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker', models.CharField(choices=[('SVART', 'Svart Marker (100)'), ('GRON', 'Grön Marker (50)'), ('ROD', 'Röd Marker (25)')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='herrklubb.bucketitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bucket Vote',
                'verbose_name_plural': 'Bucket Votes',
            },
        ),
        migrations.CreateModel(
            name='HerrklubbEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Aktivitetsnamn')),
                ('description', models.TextField(blank=True, verbose_name='Beskrivning')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Startdatum')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Slutdatum')),
                ('event_time', models.TimeField(blank=True, null=True, verbose_name='Tid')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Plats')),
                ('is_active', models.BooleanField(default=True, help_text='Visas som Nästa Event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='herrklubb.bucketcategory')),
                ('coordinators', models.ManyToManyField(blank=True, related_name='coordinated_events', to=settings.AUTH_USER_MODEL, verbose_name='Samordnare')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Herrklubb Event',
                'verbose_name_plural': 'Herrklubb Events',
                'ordering': ['event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profilbild / Avatar')),
                ('is_herrklubb_member', models.BooleanField(default=False, help_text='True if user is one of the 11 original Herrklubben members')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Startdatum')),
                ('end_date', models.DateField(verbose_name='Slutdatum')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Anledning (Valfritt)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hinder / Frånvaro',
                'verbose_name_plural': 'Hinder / Frånvaro',
                'ordering': ['start_date'],
            },
        ),
    ]
