# Generated by Django 6.1 on 2026-08-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herrklubb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herrklubbevent',
            name='bucket_items',
            field=models.ManyToManyField(blank=True, related_name='linked_events', to='herrklubb.bucketitem', verbose_name='Kopplade förslag/hinkmål'),
        ),
    ]
