# Generated by Django 6.1 on 2026-08-27 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herrklubb', '0002_herrklubbevent_bucket_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='herrklubbevent',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participating_events', to=settings.AUTH_USER_MODEL, verbose_name='Deltagare'),
        ),
    ]
