# Generated by Django 6.1 on 2026-08-28 05:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herrklubb', '0003_herrklubbevent_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='herrklubbevent',
            name='participants_no',
            field=models.ManyToManyField(blank=True, related_name='not_participating_events', to=settings.AUTH_USER_MODEL, verbose_name='Deltagare (Nej)'),
        ),
        migrations.AlterField(
            model_name='herrklubbevent',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participating_events', to=settings.AUTH_USER_MODEL, verbose_name='Deltagare (Ja)'),
        ),
    ]
