# Generated by Django 6.1 on 2026-08-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herrklubb', '0004_herrklubbevent_participants_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Smeknamn'),
        ),
    ]
