# Generated by Django 6.1 on 2026-09-03 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herrklubb', '0005_userprofile_nickname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='albums/%Y/%m/', verbose_name='Originalbild')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='albums/thumbnails/%Y/%m/', verbose_name='Miniatyrbild')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Bildtext')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='Fotograferad tidpunkt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Uppladdad tidpunkt')),
                ('tagged_members', models.ManyToManyField(blank=True, related_name='tagged_photos', to=settings.AUTH_USER_MODEL, verbose_name='Taggade medlemmar')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL, verbose_name='Uppladdad av')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Foton',
                'ordering': ['-taken_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Albumnamn / Mappnamn')),
                ('description', models.TextField(blank=True, verbose_name='Beskrivning / Notering')),
                ('folder_date', models.DateField(blank=True, null=True, verbose_name='Datum för aktivitet/resa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Skapat datum')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_albums', to='herrklubb.bucketcategory', verbose_name='Kategori')),
                ('cover_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_albums', to='herrklubb.photo', verbose_name='Omslagsbild')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_photo_albums', to=settings.AUTH_USER_MODEL, verbose_name='Skapad av')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_albums', to='herrklubb.herrklubbevent', verbose_name='Kopplat Event')),
            ],
            options={
                'verbose_name': 'Fotoalbum / Mapp',
                'verbose_name_plural': 'Fotoalbum & Mappar',
                'ordering': ['-folder_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='herrklubb.photoalbum', verbose_name='Album / Mapp'),
        ),
        migrations.CreateModel(
            name='PhotoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='herrklubb.photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto-gilla',
                'verbose_name_plural': 'Foto-gillamarkeringar',
                'unique_together': {('photo', 'user')},
            },
        ),
    ]
